# Generated by Django 6.0.2 on 2026-02-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": ["-id"]},
        ),
    ]
