# Generated by Django 6.0.2 on 2026-02-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetrydata",
            name="metric_value",
            field=models.FloatField(),
        ),
    ]
