# Generated by Django 6.0.2 on 2026-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_alter_telemetrydata_metric_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telemetrydata",
            options={"ordering": ["-timestamp"]},
        ),
    ]
