name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: True
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_URL: redis://127.0.0.1:6379/0  # ← برای django-redis

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: iot_device_database
          POSTGRES_USER: iot_user
          POSTGRES_PASSWORD: strongpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U iot_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (Code Style Check)
        run: black --check .

      - name: Wait for Postgres and Redis to be ready
        run: |
          # کمی زمان میده تا سرویس‌ها بالا بیان
          sleep 10

      - name: Run Migrations
        run: python iot_device_management/manage.py migrate

      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest iot_device_management/tests --tb=short -q
